---
defaultContentLanguage: "en"
languageCode: "en-us"
title: "Voltage Noir - Waiting Room"
copyright: '<a href="http://www.apache.org/licenses/LICENSE-2.0.txt" target="_blank" rel="noopener">© 2021 Paul Hirsch</a>'
baseurl: "/"

theme: hallo

enableRobotsTXT: true

author:
  name: "Busy"

params:
  greeting: Please Wait...
  refresh: 5

