---
defaultContentLanguage: "en"
languageCode: "en-us"
title: "Voltage Noir - Waiting Room"
copyright: '<a href="http://www.apache.org/licenses/LICENSE-2.0.txt" target="_blank" rel="noopener">© 2021 Paul Hirsch</a>'

# Note - This is overridden in the build to publish to a subdirectory
baseurl: "/"

theme: hallo

enableRobotsTXT: true

author:
  name: "Busy"

params:
  greeting: Please Wait...
  refresh: 5
  colors:
    background: "#eeeeee"
    foreground: "#333333"

